### ISSUE TITLE
How 'mature' is package?

### ISSUE THREAD

**Issue by londoh** [faustbrian/Laravel-Browsershot#11]
Hi

I jumped on this as it seemed to do exactly what I needed without me reinventing wheel etc.

But it seems as tho its maybe still a work in progress. 
So I wondered if you have any work not yet committed or plans to do more to the package?

thanks

l.

**Comment by faustbrian** [comment]
I haven't commited much since 10 months ago because the package is doing what it is supposed to do, there are no plans for new features at the moment.
